### ISSUE TITLE
Separate Contact Page

### ISSUE THREAD

**Issue by chinmaym07** [anitab-org/bridge-in-tech-web#163] opened 2021-01-28 10:44 UTC
**Is your feature request related to a problem? Please describe.**

 Separate Contact Page

**Describe the solution you'd like**
BIT should have a separate contact page as when a user clicks on contact button he is directed to the contact page of official website of Anitab.org .
Right Now As no contact page is there ,this might have a bad impact on user experience.

**Comment by mtreacy002** [comment] 2021-01-30 05:01
@chinmaym07 , I think this depends on whether or not AnitaB.org have dedicated staff to manage the incoming emails/communications from users for each of their projects. Atm, BIT is using [contact point of AnitaB](https://anitab.org/contact/) since we know there'll be someone on that end that will be able to redirect users queries to specific project admins. Perhaps in the future, once our admins confirm that we have a dedicated contact point for our project, we can develop the appropriate contact page for this. 
Although, I would also like to hear @anitab-org/admins  point of view on this one 😉.

**Comment by chinmaym07** [comment] 2021-01-30 09:52
@mtreacy002 Can we use the endpoint that is used by dedicated staff to receive emails and make our contact page and redirect our requests to that endpoint. ?

**Comment by mtreacy002** [comment] 2021-01-31 09:54
mmm.... I think the @anitab-org/admins have the answer to that, @chinmaym07. It would be great if we can 😉

**Comment by mtreacy002** [comment] 2021-04-05 00:30
@chinmaym07, I'm closing this issue now as I believe the issue is now addressed through issue #214.

**Closed as completed by mtreacy002** 2021-04-05 00:30 UTC
Labels: Category: User Interface, Type: Enhancement, Status: Possible Future Feature, Help Wanted
