### ISSUE TITLE
Bug: 404 Page overlapping the Navbar

### ISSUE THREAD

**Issue by Rahulm2310** [anitab-org/bridge-in-tech-web#187] opened 2021-03-03 19:42 UTC
**Describe the bug**
404 Error Page overlaps the navbar on small screen sizes.

**To Reproduce**
1. Go to any unavailable route for ex: http://localhost:3000/test
2. Shrink down the screen size to see error

**Expected behavior**
404 Error page should not overlap the navbar.

**Screenshots**
![bit-404](https://user-images.githubusercontent.com/54268438/109862560-960f9e80-7c86-11eb-9d40-34ff2476adb3.gif)

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version : Any

**Comment by Rahulm2310** [comment] 2021-03-03 19:43
@mtreacy002 Can you please confirm/approve this issue.

**Comment by mtreacy002** [comment] 2021-03-04 06:40
@Rahulm2310 , thank for pointing this out. This seems like a valid issue, should we label it "First timers only" issue? This would involve an easy fix right?

**Comment by Rahulm2310** [comment] 2021-03-04 06:55
@mtreacy002 yeah, it is a good first timers only issue.

**Comment by aditisingh2412** [comment] 2021-03-04 12:59
Can I work on this issue? And can you guide me a little bit to it?

**Comment by mtreacy002** [comment] 2021-03-04 22:20
Sure, @aditisingh2412 , I'll assign you on this. Feel free to ask if you have question, here or on Zulip 😉.

**Comment by Rahulm2310** [comment] 2021-03-09 09:15
@aditisingh2412 Can you please share updates on your progress.

**Comment by aditisingh2412** [comment] 2021-03-09 10:01
> @aditisingh2412 Can you please share updates on your progress.

Not able to setup. Kindly unassign me for now :)

**Comment by pratik9333** [comment] 2021-03-09 11:24
Can I fix this issue?

**Comment by mtreacy002** [comment] 2021-03-09 11:43
Thanks, @aditisingh2412 for letting us know. Unassigning you for now. Please don't hesitate to post your question on zulip  bridge-in-tech stream for help.
@pratik9333 , assigning you now.

**Comment by pratik9333** [comment] 2021-03-10 07:43
Thankyou mam

**Comment by mtreacy002** [comment] 2021-03-13 02:57
@pratik9333 , can you please give us an update on this?

**Comment by dcs-soni** [comment] 2021-03-13 09:50
Hii, If the issue is still not solved I would like to work on this issue.

**Comment by pratik9333** [comment] 2021-03-13 09:58
> @pratik9333 , can you please give us an update on this?
sorry mam couldn't able to do it due to time issue, you can assign it to someone else sorry mam

**Comment by mtreacy002** [comment] 2021-03-13 13:06
That's Ok, @pratik9333 . Thank you for letting us now 😉. @dcs-soni, I've just assigned you to backend issue [# 213](https://github.com/anitab-org/bridge-in-tech-backend/issues/213), you can focus working on that one first. Once you've submit a PR on that one, you can look for another available issue while waiting for that PR to be reviewed.

**Comment by sanjay270899** [comment] 2021-03-13 13:46
@mtreacy002 I would Like to working on this issue. I am pretty sure that I will be able to solve this issue.

**Comment by mtreacy002** [comment] 2021-03-13 13:50
Sure, @sanjay270899 , will assign you to this. Thanks for picking up the issue 😉

**Closed as completed** 2021-04-05 03:49 UTC
Labels: Category: User Interface, First Timers Only, Type: Bug
