### ISSUE TITLE
Bug: register page allow user to be both mentor and mentee

### ISSUE THREAD

**Issue by nlok5923** [anitab-org/bridge-in-tech-web#188] opened 2021-03-04 10:12 UTC
**Describe the bug**
Currently user can choose both option being a mentor as well as mentee.

**To Reproduce**
1. Go to Landing page
2. Click on register
3. Choose mentor and mentee option

**Expected behavior**
User should be able to select only one option if user tries to select both then the previously selected one should be cleared.

**Screenshots**
![image](https://user-images.githubusercontent.com/56120084/109948118-04447780-7d00-11eb-8193-6a7528d82775.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser [e.g. chrome, safari]: all
 - Version 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: all
 - OS: [e.g. iOS8.1]: all
 - Browser [e.g. stock browser, safari]: all

**Additional context**
If user is trying to select both options previously selected option should be cleared.

**Comment by fazer1929** [comment] 2021-03-04 14:15
I can fix this, can you please assign it to me?

**Comment by decon-harsh** [comment] 2021-03-04 14:21
Umm I don't seem a problem in this . A person can be both Mentor (is ready to mentor for Work A) and Mentee (needs mentoring on Work B ) . Clearify once with others

**Comment by Rahulm2310** [comment] 2021-03-04 17:27
@nlok5923 I think this is expected behaviour and not a bug. A user can be both a mentor as well as mentee. 
@mtreacy002 Can you please clearify

**Comment by mtreacy002** [comment] 2021-03-04 21:00
@nlok5923 , @Rahulm2310, @decon-harsh and @fazer1929 . This is the expected behaviour when a user register. User can say they're able to be either mentor or mentee or both. This is also the expected behaviour on Mentorship System. I'm closing this issue now.

**Closed as completed by mtreacy002** 2021-03-04 21:00 UTC
